FROM node:26-alpine AS builder

WORKDIR /app

COPY .. ./

RUN npm run build

# Второй этап

FROM nginx:alpine AS running

WORKDIR /app

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]